blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name= 'all_blog'),
    path('<int:blog_id>/', views.detail_blog, name="detail"),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name= 'home'),
    path('blog/', include('blog.urls')),
    path('contact/', views.contact, name= 'contact-detail')
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length= 100)
    date = models.DateField()
    description = models.TextField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.

def all_blogs(request):
    instances = Blog.objects.all()
    return render(request, 'blog/blog-page.html', {'instances' : instances})

def detail_blog(request, blog_id):
    instance = get_object_or_404(Blog, pk= blog_id)
    return render(request, 'blog/detail.html', {'instance': instance})

portfolio/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'portfolio/index.html')

def contact(request):
    return render(request, 'portfolio/contact.html')

blog/templates/blog/blog-page.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}
<div class="container blogs">
    <div class="blockquote text-center">
        <h1>ब्लग खण्ड</h1>
        <h2>हामी संग अहिले मात्र {{instances.count}} ओटा ब्लग छ</h2>
    </div>
    <ul>
        {% for instance in instances %}
        <p>
            <li>
                <h1 class="title-heading">{{instance.title}} <span class="badge badge-secondary">नयाँ</span></h1>
                <h2 class="blockquote-footer">{{instance.date|date:"M j Y"|upper}}</h2>
                <h3>{{instance.description|truncatechars:100}}</h3>
                <a href="{% url 'blog:detail' instance.id %}">पुरा पढ्नुहोस्....</a>
            </li>
        </p>
        {% endfor %}
    </ul>
</div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% block content %}
<div class="container blog-detail">
    <a href="{% url 'blog:all_blog' %}">फिर्ता...</a>
    <h1>{{instance.title}}</h1>
    <h2>--{{instance.date|date:"F j Y"}}--</h2>
    <h3>{{instance.description}}</h3>
</div>
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bibek's Portfolio</title>
    <link rel="stylesheet" href="{% static 'portfolio/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'portfolio/css/base_style.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/blog_style.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/contact-css.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png" href="{% static 'portfolio/images/face.png' %}">
</head>

<body>
    <header class="header_area">
        <div class="main-menu">
            <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'portfolio/images/logo.png' %}" alt="logo" id="logo" width="150px">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'home' %}">होम<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#intro">परिचय</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#services">सेवाहरु</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#client">ग्राहकको प्रतिक्रिया</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:all_blog' %}">ब्लग</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% static 'portfolio/resume/Resume.pdf' %}" target="_blank">बायो डाटा</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contact-detail' %}">सम्पर्क/ठेगाना</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    {% block content %} 
    {% endblock %}

    <footer class="footer-area">
        <div class="container">
            <div>
                <div class="social text-center">
                    <h5 class="text-uppercase">Follow me on</h5>
                    <a href="https://www.facebook.com/bibek.pandit.37" target="_blank"><img src="{% static 'portfolio/images/facebook.png' %}" alt="facebook"></a>
                    <a href="https://www.instagram.com/bibekpandit796/" target="_blank"><img src="{% static 'portfolio/images/instagram.png' %}" alt="instagram"></a>
                </div>
                <div class="copyrights text-center">
                    <p class="para">
                        Copyright &#169;2020 All rights reserved | This template is made with by <a href="#"><span>Pandit
                Jee</span></a>
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="{% static 'portfolio/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'portfolio/js/main.js' %}"></script>
</body>

</html>

portfolio/templates/portfolio/contact.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}
<div class="container contact-details">
    <div class="blockquote text-center contact-heading">
        सम्पर्क / ठेगाना
    </div>
    <div class="card container" style="width: 18rem;">
        <img src="{% static 'portfolio/images/bibek-pandit.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">बिबेक पण्डित</h5>
            <p class="card-text">ज्योतिष विज्ञ / कम्प्युटर ईन्जिनियर</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">फोन नम्बर: <a href="#">९८४६७०८९३०</a></li>
            <li class="list-group-item">ईमेल: <a href="#">bibekpandit@hariom.com</a></li>
            <li class="list-group-item">ठेगाना: <a href="#">सिमौलचौर, पोखरा</a></li>
        </ul>
        <div class="card-body">
            <a href="https://goo.gl/maps/YaMRtX3hRzzGo37i8" target="_blank" class="card-link">नक्शामा हेर्नुहोस्</a>
        </div>
    </div>
</div>
{% endblock %}

portfolio/templates/portfolio/index.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}

<!--  ======================= Start Banner Area =======================  -->
<main class="site-main">
    <section class="site-banner">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-12 site-title">
                    <h3 class="title-text">नमस्ते</h3>
                    <h1 class="title-text text-uppercase">म बिबेक पण्डित</h1>
                    <h4 class="title-text text-uppercase">ज्योतिष विज्ञ</h4>
                    <div class="site-buttons">
                        <div class="d-flex flex-row flex-wrap">
                            <button type="button" class="btn button primary-button mr-4 text-uppercase">hire
                                me</button>
                            <button type="button" class="btn button secondary-button text-uppercase"
                                onclick="window.location.href='{% static 'portfolio/resume/Resume.pdf' %}';">बायो
                                डाटा</button>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12 banner-image">
                    <img src="{% static 'portfolio/images/cover.jpg' %}" alt="banner-img" class="img-fluid">
                </div>
            </div>
        </div>
    </section>
    <!--  ======================= End Banner Area =======================  -->

    <!--  ========================= About Area ==========================  -->
    <a name="intro"></a>
    <section class="about-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 col-md-12">
                    <div class="about-image">
                        <img src="{% static 'portfolio/images/bibek-pandit.jpg' %}" alt="About us" class="img-fluid">
                    </div>
                </div>
                <div class="col-lg-6 col-md-12 about-title">
                    <h2 class="text-uppercase pt-5">
                        <span>पहिला</span>
                        <span>आफ्नो परिचय</span>
                        <span>दिन्छु</span>
                    </h2>
                    <div class="paragraph py-4 w-75">
                        <p class="para">
                            नमस्कार म बिबेक पण्डित। मेरो उमेर २१ वर्ष हो। मेरो घर सिमौलचौर, पोखरा हो। मेरो जन्म रुपाकोट,
                            पोखरामा भएको ह।
                        </p>
                        <p class="para">
                            मेरो हजुरबुवा पुजारी भएको कारणले म उहाको काम बाट प्रेरित भएर मैले पनि पण्डित बन्नको लागि
                            चाहिनी सम्पूर्ण ज्ञान सिके।
                            नेपालमा सबै जसो पण्डितहरु पढे नलेखहेको भएको कारणले मैले ईन्जिनियरइंग पदने सोचे र अहिले म
                            कम्प्युटर ईन्जिनियरइंग पड्दै छ।
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!--  ========================= End About Area ==========================  -->

    <!--  ====================== Start Services Area =============================  -->

    <a name="services"></a>
    <section class="services-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center services-title">
                    <h1 class="text-uppercase title-text">सेवा सुबिदाहरु</h1>
                    <p class="para">
                        ग्राहकको खुसि नै हाम्रो खुसि हो तेसैले बिगत ५ वर्ष देखि हाम्ले ग्राहकलाई सुपत मूल्यमा गुदस्तरिय
                        सेवा दिदै आएका छौ।
                    </p>
                </div>
            </div>
            <div class="container services-list">
                <div class="row">
                    <div class="col-lg-3 col-md-6 col-sm-12">
                        <div class="services">
                            <div class="sevices-img text-center py-4">
                                <img src="{% static 'portfolio/images/wedding.png' %}" alt="Services-1">
                            </div>
                            <div class="card-body text-center">
                                <h5 class="card-title text-uppercase font-roboto">बिबाह</h5>
                                <p class="card-text text-secondary">
                                    बिबाहको लागि पण्डित आवश्यक परेको खण्डमा हामीलाई सम्झनु होस्।
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-12">
                        <div class="services">
                            <div class="sevices-img text-center py-4">
                                <img src="{% static 'portfolio/images/bald.png' %}" alt="Services-2">
                            </div>
                            <div class="card-body text-center">
                                <h5 class="card-title text-uppercase font-roboto">बर्तबन्द</h5>
                                <p class="card-text text-secondary">
                                    बर्तबन्द लागि पण्डित आवश्यक परेको खण्डमा हामीलाई सम्झनु होस्।
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-12">
                        <div class="services">
                            <div class="sevices-img text-center py-4">
                                <img src="{% static 'portfolio/images/future.png' %}" alt="Services-3">
                            </div>
                            <div class="card-body text-center">
                                <h5 class="card-title text-uppercase font-roboto">भविष्य हेराउनी</h5>
                                <p class="card-text text-secondary">
                                    तपाईलाई आफ्नो अथवा कसैको भविष्य हेराउनु परेमा हामीलाई सम्झनुहोस।
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-12">
                        <div class="services">
                            <div class="sevices-img text-center py-4">
                                <img src="{% static 'portfolio/images/magic.png' %}" alt="Services-4">
                            </div>
                            <div class="card-body text-center">
                                <h5 class="card-title text-uppercase font-roboto">अन्य</h5>
                                <p class="card-text text-secondary">
                                    सबै पुजा पाठ सम्बंदी पनि हामी सेवा दिन्क्ष।
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!--  ====================== End Services Area =============================  -->

    <!--  ======================== Client Area ==============================  -->
    <a name="client"></a>
    <section class="about-area">
        <div class="container">
            <div class="row text-center">
                <div class="col-12">
                    <div class="about-title">
                        <h1 class="text-uppercase title-h1">ग्राहकको प्रतिक्रिया मेरो काम प्रति</h1>
                        <p class="para">
                            केहि प्रतिक्रियाहरु छन् मेरा आदरणीय ग्राहक महानुभाब बाट मेरो काम प्रति। ग्राहकको सन्तुष्टिनै मेरो सन्तुष्टि ह।
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="container carousel py-lg-5">
            <div class="owl-carousel owl-theme">
                <div class="client row">
                    <div class="col-lg-4 col-md-12 client-img">
                        <img src="{% static 'portfolio/images/maili.jpg' %}" alt="img1" class="img-fluid">
                    </div>
                    <div class="col-lg-8 col-md-12 about-client">
                        <h4 class="text-uppercase">सुरक्ष्या अधिकारी</h4>
                        <p class="para">मेरो भाईको बर्तबन्द सस्तो, भर पर्दो, गुदस्तरिय र सुपत मूल्यमा गरिदिनु भयो।  उहाको कल्याण होस।</p>
                    </div>
                </div>
                <div class="client row">
                    <div class="col-lg-4 col-md-12 client-img">
                        <img src="{% static 'portfolio/images/sunita.jpg' %}" alt="img2" class="img-fluid">
                    </div>
                    <div class="col-lg-8 col-md-12 about-client">
                        <h4 class="text-uppercase">सुनिता राना</h4>
                        <p class="para">उहा संग मैले मेरो भविष्य हेराए र पक्षि उहाले भनेको जस्तै ठ्याक्कै पर्यो।</p>
                    </div>
                </div>
                <div class="client row">
                    <div class="col-lg-4 col-md-12 client-img">
                        <img src="{% static 'portfolio/images/subash.jpg' %}" alt="img1" class="img-fluid">
                    </div>
                    <div class="col-lg-8 col-md-12 about-client">
                        <h4 class="text-uppercase">सुबाश तिमिल्सिना</h4>
                        <p class="para">पहिला मेरो भैसीले दूध थोरै दिन थियो र पक्षि उहाले दिएको खिर भैसीलाई खुलाए पक्षि दूध धेरै दिन थालेको छ।</p>
                    </div>
                </div>
                <div class="client row">
                    <div class="col-lg-4 col-md-12 client-img">
                        <img src="{% static 'portfolio/images/oldman.jpg' %}" alt="img2" class="img-fluid">
                    </div>
                    <div class="col-lg-8 col-md-12 about-client">
                        <h4 class="text-uppercase">हरि चापागाईं</h4>
                        <p class="para">गुरुले मेरो भागी बिबाह मन्दिरमा गरिदिएको कारण आजको दिन सम्म मेरो र बुडीको सम्बन्द राम्रो ।</p>
                    </div>
                </div>
            </div>
        </div>

    </section>
</main>

{% endblock %}